// <auto-generated />
namespace Magicodes.Models.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Add_PlusId_to_Nav_SiteAdminNavigation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_PlusId_to_Nav_SiteAdminNavigation));
        
        string IMigrationMetadata.Id
        {
            get { return "201501050841534_Add_PlusId_to_Nav_SiteAdminNavigation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
