// <auto-generated />
namespace Magicodes.CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddChannelId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChannelId));
        
        string IMigrationMetadata.Id
        {
            get { return "201501080419232_AddChannelId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
