// <auto-generated />
namespace Magicodes.Models.Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BlogUser_DeleteTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogUser_DeleteTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201411060542156_BlogUser_DeleteTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
